url="https://blpaukpvavuuirotngcr.supabase.co"
key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscGF1a3B2YXZ1dWlyb3RuZ2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxNDE2NzUsImV4cCI6MjA0NzcxNzY3NX0.JvcJ8SOJha27oHUwiAlDie8MQu3vwbwfXth1eZqSaWk"

